sudo: required
services:
  - docker
language: bash
script:
  - docker build -t grimkriegor/tes3mp-server .
  - >
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKERHUB_PASS" | docker login -u="$DOCKERHUB_USER" --password-stdin
      TAG=$(grep "ENV TES3MP_VERSION" Dockerfile | awk 'NF>1{print $NF}')
      docker tag grimkriegor/tes3mp-server grimkriegor/tes3mp-server:$TAG
      docker push grimkriegor/tes3mp-server:$TAG
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker push grimkriegor/tes3mp-server
      fi
    fi
